-- =========================================================================
-- SEED EQUIPMENT DATA FROM PDF EXPORT
-- Run this in your Supabase SQL Editor to populate/sync your equipment database.
-- =========================================================================

-- 1. Ensure all equipment categories exist
INSERT INTO equipment_categories (name, description) VALUES 
('Excavator', 'Heavy construction equipment used for digging and earthmoving'), 
('Dump Truck', 'Large trucks designed for transporting loose material'), 
('Dozer', 'Powerful tracked tractors with a large blade'), 
('Loader', 'Heavy machinery used to move or load materials'), 
('Grader', 'Construction machine with a long blade used to create a flat surface'), 
('Light Vehicle', 'Standard utility vehicles and trucks'), 
('Crane', 'Heavy lifting and hoisting machinery'), 
('Telehandler', 'Telescopic handlers used for lifting and material handling'), 
('Forklift', 'Industrial trucks used to lift and move materials over short distances'), 
('Sweeper', 'Industrial road and surface sweeping machines'), 
('Compactor', 'Soil and asphalt compaction machinery'), 
('Paver', 'Asphalt paving and laying machinery'), 
('Recycler', 'Industrial waste and material recycling machinery'), 
('Cherrypicker', 'Aerial work platforms and boom lifts')
ON CONFLICT (name) DO NOTHING;

-- 2. Ensure all operators exist
INSERT INTO operators (name, status)
SELECT name, 'Active'
FROM (
  VALUES 
    ('KODA Wenneng'),
    ('Jingye Qi'),
    ('CHRIS Kabongo'),
    ('CHRISTOS Loannou'),
    ('ION Muzama'),
    ('KANDURI Antonio'),
    ('TEDDY Bin Njojo'),
    ('Alfred Ngoie'),
    ('ELIAS Johannes Nel'),
    ('Andre Heydenrych'),
    ('Paulin Mulaj'),
    ('JUDD Barlow'),
    ('Marcel Van Niekerk')
) AS new_ops(name)
WHERE NOT EXISTS (
  SELECT 1 FROM operators WHERE operators.name = new_ops.name
);

-- 3. Insert or update the 125 equipment records
INSERT INTO equipment (
  asset_tag, 
  type, 
  model, 
  manufacturer, 
  year, 
  serial_number, 
  current_location, 
  status, 
  category_id, 
  assigned_operator_id
) 
VALUES 
-- Page 1 Rows
('SM-CR001', 'SANY TRUCK CRANE', 'STC1000S', 'SANY', 2019, 'TC0100BH2386', 'KAKULA CONSTRUCTION', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Crane' LIMIT 1), (SELECT id FROM operators WHERE name = 'KODA Wenneng' LIMIT 1)),
('SM-TLH001', 'TELEHANDLER', 'MT-X1033', 'MANITOU', 2021, 'MAN00000C0104485', 'SUPPLIER CHAIN', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Telehandler' LIMIT 1), (SELECT id FROM operators WHERE name = 'Jingye Qi' LIMIT 1)),
('SM-FL001', 'WHEELLOADER', 'L25F', 'VOLVO', 2019, 'VCE0L25FP01758648', 'SUPPLIER CHAIN', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Loader' LIMIT 1), (SELECT id FROM operators WHERE name = 'Jingye Qi' LIMIT 1)),
('SM-CR002', 'ROUGH TERRAIN CRANE', 'SRC900C', 'SANY', 2020, 'RC0090CA0421', 'ENGINEERING CONCENTRATOR', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Crane' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRIS Kabongo' LIMIT 1)),
('SM-FKL001', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2019, '608FDJ35-74042', 'SUPPLIER CHAIN', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'Jingye Qi' LIMIT 1)),
('SM-FKL002', 'FORKLIFT', 'EG 3.0T', 'EUROLIFT', 2020, 'A6V1A01698J', 'SUPPLIER CHAIN', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'Jingye Qi' LIMIT 1)),
('SM-TLH002', 'TELEHANDLER', 'MTH-X790', 'MANITOU', 2021, 'MAN00000L00776458', 'KAKULA CONSTRUCTION', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Telehandler' LIMIT 1), (SELECT id FROM operators WHERE name = 'KODA Wenneng' LIMIT 1)),
('SM-FKL003', 'FORKLIFT', 'M-X50', 'MANITOU', 2019, 'MAN00000C01028492', 'SUPPLIER CHAIN', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'Jingye Qi' LIMIT 1)),
('SM-TLH003', 'TELEHANDLER', 'MT-X1840', 'MANITOU', 2019, 'MAN00000C01029733', 'ENGINEERING CONCENTRATOR', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Telehandler' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRIS Kabongo' LIMIT 1)),
('SM-FKL004', 'FORKLIFT', 'MI-X70D', 'MANITOU', 2019, 'MAN00000V00875570', 'SUPPLIER CHAIN', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'Jingye Qi' LIMIT 1)),
('SM-FKL005', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2020, '708FDJ35-63849', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL006', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2020, '708FDJ35-80090', 'PROCESS KAMOA1 PLANT', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'ION Muzama' LIMIT 1)),
('SM-FKL007', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2020, '708FDJ35-80144', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL008', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2020, '708FDJ35-80119', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL009', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2020, '708FDJ35-80118', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL010', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2020, '708FDJ35-80116', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL011', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2021, '708FDJ35-80115', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL012', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2020, '608FDJ35-81250', 'KANSOKO TRAINING CENTER', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'KANDURI Antonio' LIMIT 1)),
('SM-FKL013', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2020, '708FDJ35-80113', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL014', 'FORKLIFT', 'MI-X50D', 'MANITOU', 2021, 'MAN00000L00885311', 'SUPPLIER CHAIN', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'Jingye Qi' LIMIT 1)),
('SM-FKL015', 'FORKLIFT', '940-4 T4', 'JCB', 2022, 'JCB94004TM2932114', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL016', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2022, '708FDJ35-80388', 'SUPPLIER CHAIN', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'Jingye Qi' LIMIT 1)),
('SM-FKL017', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2022, '708FDJ35-80561', 'PROCESS KAKULA PLANT', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'TEDDY Bin Njojo' LIMIT 1)),
('SM-FKL018', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2020, '708FDJ35-61614', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL019', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2022, '708FDJ35-80806', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-TLH004', 'TELEHANDLER', 'MHT-X790', 'MANITOU', 2022, 'MAN00000H0103815', 'BACKFIL KAKULA', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Telehandler' LIMIT 1), (SELECT id FROM operators WHERE name = 'Alfred Ngoie' LIMIT 1)),
('SM-FKL020', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2022, '80133', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL021', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2022, '708FDJ35-80738', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL022', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2022, '708FDJ35-80742', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL023', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2021, '708FDJ35-80804', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL024', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2022, '708FDJ35-80862', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL025', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2022, '708FDJ35-80855', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-TLH005', 'TELEHANDLER', 'MHT-X790', 'MANITOU', 2022, 'MAN00000C01068328', 'PROCESS KAKULA PLANT', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Telehandler' LIMIT 1), (SELECT id FROM operators WHERE name = 'TEDDY Bin Njojo' LIMIT 1)),
('SM-TLH006', 'TELEHANDLER', 'MHT-X790', 'MANITOU', 2022, 'MAN00000TOO777924', 'ENGINEERING CONCENTRATOR', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Telehandler' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRIS Kabongo' LIMIT 1)),
('SM-CR003', 'SANY CRANE', 'STC300C5', 'SANY', 2022, 'LFCNLE5P8N2003483', 'ENGINEERING CONCENTRATOR', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Crane' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRIS Kabongo' LIMIT 1)),
('SM-CR004', 'LIFTING MACHINE', 'SRSC45V', 'SANY', 2022, 'RS4501CC0092', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Crane' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-CR005', 'LIFTING MACHINE', 'SRSC45V', 'SANY', 2022, 'RS4501CC0086', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Crane' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-TLH007', 'TELEHANDLER', 'MXT1740', 'MANITOU', 2022, 'TEP1740PLN3000284', 'SUPPLIER CHAIN', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Telehandler' LIMIT 1), (SELECT id FROM operators WHERE name = 'Jingye Qi' LIMIT 1)),
('SM-TLH008', 'TELEHANDLER', 'MXT1740', 'MANITOU', 2022, 'TEP1740PCM5000137', 'KAMOA 1 MINES SHAFT CONSTRUCTION', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Telehandler' LIMIT 1), (SELECT id FROM operators WHERE name = 'ELIAS Johannes Nel' LIMIT 1)),
('SM-TLH009', 'TELEHANDLER', 'MHT-X790', 'MANITOU', 2020, 'MAN000001053475', 'TM3 WORKSHOP', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Telehandler' LIMIT 1), (SELECT id FROM operators WHERE name = 'Andre Heydenrych' LIMIT 1)),
('SM-TLH010', 'TELEHANDLER', 'MHT-X790', 'MANITOU', 2020, 'MAN00000C00774818', 'TM3 WORKSHOP', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Telehandler' LIMIT 1), (SELECT id FROM operators WHERE name = 'Andre Heydenrych' LIMIT 1)),
('SM-RCL001', 'RECYCLER', 'KL2-SP1/4/24V', 'KONVEKTA', 2000, '113740-2', 'ENGINEERING SURFACE WORKSHOP', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Recycler' LIMIT 1), (SELECT id FROM operators WHERE name = 'Paulin Mulaj' LIMIT 1)),
('SM-RL001', 'ROLLER COMPACTOR', 'ROLLER', 'PNEUMATI', 2000, '27033', 'ENGINEERING SURFACE WORKSHOP', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Compactor' LIMIT 1), (SELECT id FROM operators WHERE name = 'Paulin Mulaj' LIMIT 1)),
('SM-RL002', 'ROLLER COMPACTOR', 'ROLLER', 'PNEUMATI', 2000, 'H1761739', 'ENGINEERING SURFACE WORKSHOP', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Compactor' LIMIT 1), (SELECT id FROM operators WHERE name = 'Paulin Mulaj' LIMIT 1)),
('SM-PV001', 'WHEELED PAVER', '251P', 'MARINI', 2000, '196-90', 'ENGINEERING SURFACE WORKSHOP', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Paver' LIMIT 1), (SELECT id FROM operators WHERE name = 'Paulin Mulaj' LIMIT 1)),
('SM-FKL026', 'FORKLIFT', 'SAS 50', 'TOYOTA', 2023, '30FD50N-21303', 'SUPPLIER CHAIN', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'Jingye Qi' LIMIT 1)),
('SM-FKL027', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2023, '708FDJ35-81161', 'SUPPLIER CHAIN', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'Jingye Qi' LIMIT 1)),

-- Page 2 Rows
('SM-CR006', 'ROUGH TERRAIN CRANE', 'SRC900T', 'SANY', 2023, 'RC0090CC0546', 'KAKULA CONSTRUCTION', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Crane' LIMIT 1), (SELECT id FROM operators WHERE name = 'KODA Wenneng' LIMIT 1)),
('SM-FKL028', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2022, '708FDJ35-81158', 'SUPPLIER CHAIN', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'Jingye Qi' LIMIT 1)),
('SM-FKL029', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2022, '708FDJ35-81238', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL030', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2022, '708FDJ35-81173', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL031', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2022, '708FDJ35-81168', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL032', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2022, '708FDJ35-81248', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL033', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2022, '708FDJ35-81245', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL034', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2022, '708FDJ35-81251', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL035', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2022, '708FDJ35-81204', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL036', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2022, '708FDJ35-81214', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL037', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2022, '708FDJ35-81546', 'SUPPLIER CHAIN', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'Jingye Qi' LIMIT 1)),
('SM-FKL038', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2022, '708FDJ35-81450', 'ENGINEERING SURFACE WORKSHOP', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'Paulin Mulaj' LIMIT 1)),
('SM-FKL039', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2022, '708FDJ35-81559', 'ENGINEERING SURFACE WORKSHOP', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'Paulin Mulaj' LIMIT 1)),
('SM-SWP001', 'MACHINE SWEPT DULEVO', '850 DK', 'DULEVO', 2023, 'ZA9850DK00NC38240', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Sweeper' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-CR007', 'TRUCK CRANE', 'SAC4500S', 'SANY', 2022, 'LFCNRGAP3N2003908', 'ENGINEERING CONCENTRATOR', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Crane' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRIS Kabongo' LIMIT 1)),
('SM-TLH011', 'TELEHANDLER', 'MHT-X790', 'MANITOU', 2023, 'MAN00000T01080408', 'KAKULA CONSTRUCTION', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Telehandler' LIMIT 1), (SELECT id FROM operators WHERE name = 'KODA Wenneng' LIMIT 1)),
('SM-TLH012', 'TELEHANDLER', 'MHT-X790', 'MANITOU', 2023, 'MAN00000K01077804', 'ENGINEERING TM3 WORKSHOP', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Telehandler' LIMIT 1), (SELECT id FROM operators WHERE name = 'Andre Heydenrych' LIMIT 1)),
('SM-TLH013', 'TELEHANDLER', 'MHT-X 10200', 'MANITOU', 2023, 'MAN00000J01088299', 'KAKULA CONSTRUCTION', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Telehandler' LIMIT 1), (SELECT id FROM operators WHERE name = 'KODA Wenneng' LIMIT 1)),
('SM-TLH014', 'TELEHANDLER', 'MT-X 1840 A', 'MANITOU', 2023, 'MAN00000C01097563', 'PROCESS KAMOA1 PLANT', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Telehandler' LIMIT 1), (SELECT id FROM operators WHERE name = 'ION Muzama' LIMIT 1)),
('SM-FKL040', 'FORKLIFT', '940-4 T4', 'JCB', 2023, 'JCB94004AM2932199', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-TLH015', 'TELEHANDLER', 'MXT 840', 'MANITOU', 2022, 'TEP0840PC01095074', 'SUPPLIER CHAIN', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Telehandler' LIMIT 1), (SELECT id FROM operators WHERE name = 'Jingye Qi' LIMIT 1)),
('SM-FKL041', 'FORKLIFT', 'SAS 50', 'TOYOTA', 2023, '8FD50N', 'SUPPLIER CHAIN', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'Jingye Qi' LIMIT 1)),
('SM-TLH016', 'TELEHANDLER', 'MHT-X790', 'MANITOU', 2023, 'MAN00000A01087867', 'SUPPLIER CHAIN', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Telehandler' LIMIT 1), (SELECT id FROM operators WHERE name = 'Jingye Qi' LIMIT 1)),
('SM-TLH017', 'TELEHANDLER', 'MHT-X790', 'MANITOU', 2023, 'MAN00000C01086988', 'SUPPLIER CHAIN', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Telehandler' LIMIT 1), (SELECT id FROM operators WHERE name = 'Jingye Qi' LIMIT 1)),
('SM-TLH018', 'TELEHANDLER', 'MHT-X790', 'MANITOU', 2023, 'MAN00000T01082286', 'SUPPLIER CHAIN', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Telehandler' LIMIT 1), (SELECT id FROM operators WHERE name = 'Jingye Qi' LIMIT 1)),
('SM-FKL042', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2023, '708FDJ35-82019', 'SUPPLIER CHAIN', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'Jingye Qi' LIMIT 1)),
('SM-FKL043', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2023, '708FDJ35-82236', 'SUPPLIER CHAIN', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'Jingye Qi' LIMIT 1)),
('SM-FKL044', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2023, '708FDJ35-82249', 'ENGINEERING SURFACE WORKSHOP', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'Paulin Mulaj' LIMIT 1)),
('SM-FL002', 'LOADER', 'SW966K1', 'SANY', 2023, 'SW9663CDMO288', 'KAKULA STOCKPILES', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Loader' LIMIT 1), (SELECT id FROM operators WHERE name = 'JUDD Barlow' LIMIT 1)),
('SM-FL003', 'LOADER', 'SW966K1', 'SANY', 2023, 'SW9663CDM0278', 'KAMOA 1 MINES SHAFT CONSTRUCTION', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Loader' LIMIT 1), (SELECT id FROM operators WHERE name = 'ELIAS Johannes Nel' LIMIT 1)),
('SM-RL003', 'COMPACTOR', 'BW120AD', 'BOMAG', 2022, '9.6188E+11', 'ENGINEERING SURFACE WORKSHOP', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Compactor' LIMIT 1), (SELECT id FROM operators WHERE name = 'Paulin Mulaj' LIMIT 1)),
('SM-CHP001', 'CHERRYPICKER', '160ATJ', 'MANITOU', 2024, 'MAN00000K01117394', 'PROCESS KAKULA PLANT', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Cherrypicker' LIMIT 1), (SELECT id FROM operators WHERE name = 'TEDDY Bin Njojo' LIMIT 1)),
('SM-TLH019', 'TELEHANDLER', 'MHT-X790 MINING', 'MANITOU', 2024, 'MAN00000PO1109682', 'KANSOKO MINE Technical', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Telehandler' LIMIT 1), (SELECT id FROM operators WHERE name = 'Marcel Van Niekerk' LIMIT 1)),
('SM-TLH020', 'TELEHANDLER', 'MHT-X790 MINING', 'MANITOU', 2024, 'MAN00000K01109750', 'KANSOKO MINE Technical', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Telehandler' LIMIT 1), (SELECT id FROM operators WHERE name = 'Marcel Van Niekerk' LIMIT 1)),
('SM-FKL045', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2023, '708FDJ35-82223', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL046', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2023, '708FDJ35-82498', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL047', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2023, '708FDJ35-82018', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL048', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2023, '708FDJ35-82024', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL049', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2023, '708FDJ35-82229', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-TLH022', 'TELEHANDLER', 'MHT-X790', 'MANITOU', 2024, 'MAN00000V01125533', 'ENGINEERING CONCENTRATOR', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Telehandler' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRIS Kabongo' LIMIT 1)),
('SM-TLH023', 'TELEHANDLER', 'MHT-X790', 'MANITOU', 2024, 'MAN00000H01127030', 'SUPPLIER CHAIN', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Telehandler' LIMIT 1), (SELECT id FROM operators WHERE name = 'Jingye Qi' LIMIT 1)),
('SM-TLH024', 'TELEHANDLER', 'HTH 10.10-D/A', 'MAGNI', 2023, '8529', 'ENGINEERING TM3 WORKSHOP', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Telehandler' LIMIT 1), (SELECT id FROM operators WHERE name = 'Andre Heydenrych' LIMIT 1)),
('SM-TLH025', 'TELEHANDLER', 'HTH 10.10-D/A', 'MAGNI', 2023, '8271', 'ENGINEERING TM3 WORKSHOP', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Telehandler' LIMIT 1), (SELECT id FROM operators WHERE name = 'Andre Heydenrych' LIMIT 1)),
('SM-FKL050', 'FORKLIFT', 'SAS 30', 'TOYOTA', 2022, '608FDJ35-86469', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-CHP002', 'CHERRYPICKER', '280 TJ', 'MANITOU', 2015, '952703', 'ENGINEERING SURFACE WORKSHOP', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Cherrypicker' LIMIT 1), (SELECT id FROM operators WHERE name = 'Paulin Mulaj' LIMIT 1)),
('SM-FL004', 'LOADER', 'SW966K1', 'SANY', 2024, 'SW9663CEM0078', 'PROCESS KAMOA1 PLANT', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Loader' LIMIT 1), (SELECT id FROM operators WHERE name = 'ION Muzama' LIMIT 1)),
('SM-FL005', 'LOADER', 'SW966K1', 'SANY', 2024, 'SW9663CEM0088', 'PROCESS KAMOA1 PLANT', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Loader' LIMIT 1), (SELECT id FROM operators WHERE name = 'ION Muzama' LIMIT 1)),
('SM-PV002', 'ASPHALT PAVER', 'SSP90C-80', 'SANY', 2024, 'LT8790CE0403', 'ENGINEERING SURFACE WORKSHOP', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Paver' LIMIT 1), (SELECT id FROM operators WHERE name = 'Paulin Mulaj' LIMIT 1)),

-- Page 3 Rows
('SM-FKL054', 'FORKLIFT', 'CPCD50-AXG53', 'HANGCHA', 2024, '14BD52716', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL061', 'FORKLIFT', 'SAS 3.0', 'TOYOTA', 2022, '608FDJ35-86490', 'SUPPLIER CHAIN', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'Jingye Qi' LIMIT 1)),
('SM-FKL062', 'FORKLIFT', 'SAS 3.0', 'TOYOTA', 2022, '608FDJ35-86479', 'SUPPLIER CHAIN', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'Jingye Qi' LIMIT 1)),
('SM-CR008', 'ROUGH TERRAIN CRANE', 'SRC900T', 'SANY', 2024, 'RC0090CE0575', 'ENGINEERING CONCENTRATOR', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Crane' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRIS Kabongo' LIMIT 1)),
('SM-CR009', 'TRUCK CRANE', 'TC2050CE1813', 'SANY', 2024, 'LFCNNF5PXR2005709', 'ENGINEERING CONCENTRATOR', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Crane' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRIS Kabongo' LIMIT 1)),
('SM-RL004', 'PNEUMATIQUE ROLLER', 'SPR300C-8S', 'SANY', 2024, 'YZ3530CE3315', 'ENGINEERING SURFACE WORKSHOP', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Compactor' LIMIT 1), (SELECT id FROM operators WHERE name = 'Paulin Mulaj' LIMIT 1)),
('SM-TLH026', 'TELEHANDLER', 'MXT-1740', 'MANITOU', 2024, 'TEP1740PH01118454', 'PROCESS KAMOA1 PLANT', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Telehandler' LIMIT 1), (SELECT id FROM operators WHERE name = 'ION Muzama' LIMIT 1)),
('SM-FKL078', 'FORKLIFT', 'CPCD30-AG2', 'HANGCHA', 2024, '14BD45296', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL079', 'FORKLIFT', 'CPCD30-AG2', 'HANGCHA', 2024, '14BD45297', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL080', 'FORKLIFT', 'CPCD30-AG2', 'HANGCHA', 2024, '14BD45298', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL081', 'FORKLIFT', 'SAS50', 'TOYOTA', 2023, '8FD50N-22367', 'ENGINEERING SURFACE WORKSHOP', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'Paulin Mulaj' LIMIT 1)),
('SM-FKL082', 'FORKLIFT', 'G3 0430 L', 'HANGCHA', 2024, '0347D01', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL083', 'FORKLIFT', 'G2 0430 L', 'HANGCHA', 2024, '14BE06557', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL084', 'FORKLIFT', 'CPCD50-AXG53', 'HANGCHA', 2024, '14BD74347', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL085', 'FORKLIFT', 'CPCD30-AG2', 'HANGCHA', 2025, '14BE06555', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL086', 'FORKLIFT', 'CPCD30-AG2', 'HANGCHA', 2025, '14BE06556', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL087', 'FORKLIFT', 'CPCD30-AG2', 'HANGCHA', 2025, '14BE06558', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL088', 'FORKLIFT', 'CPCD30-AG2', 'HANGCHA', 2025, '14BE06559', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-EX001', 'EXCAVATOR', 'SY365H', 'SANY', 2025, 'SY036CF1159K8', 'ENGINEERING SURFACE WORKSHOP', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Excavator' LIMIT 1), (SELECT id FROM operators WHERE name = 'Paulin Mulaj' LIMIT 1)),
('SM-EX002', 'EXCAVATOR', 'SY365H', 'SANY', 2025, 'SY036CF1160K8', 'ENGINEERING SURFACE WORKSHOP', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Excavator' LIMIT 1), (SELECT id FROM operators WHERE name = 'Paulin Mulaj' LIMIT 1)),
('SM-EX003', 'EXCAVATOR', 'SY365H', 'SANY', 2025, 'SY036CF1161K8', 'ENGINEERING SURFACE WORKSHOP', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Excavator' LIMIT 1), (SELECT id FROM operators WHERE name = 'Paulin Mulaj' LIMIT 1)),
('SM-EX004', 'EXCAVATOR', 'SY365H', 'SANY', 2025, 'SY036CF1162K8', 'ENGINEERING SURFACE WORKSHOP', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Excavator' LIMIT 1), (SELECT id FROM operators WHERE name = 'Paulin Mulaj' LIMIT 1)),
('SM-EX005', 'EXCAVATOR', 'SY365H', 'SANY', 2025, 'SY036CF0730K8', 'ENGINEERING SURFACE WORKSHOP', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Excavator' LIMIT 1), (SELECT id FROM operators WHERE name = 'Paulin Mulaj' LIMIT 1)),
('SM-FKL089', 'FORKLIFT', 'CPCD30-AG2', 'HANGCHA', 2025, '14BE26236', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL090', 'FORKLIFT', 'CPCD30-AG2', 'HANGCHA', 2025, '14BE26237', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL091', 'FORKLIFT', 'CPCD30-AG2', 'HANGCHA', 2025, '14BE26239', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL092', 'FORKLIFT', 'CPCD30-AG2', 'HANGCHA', 2025, '14BE39271', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL093', 'FORKLIFT', 'CPCD30-AG2', 'HANGCHA', 2025, '14BE39272', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL094', 'FORKLIFT', 'CPCD30-AG2', 'HANGCHA', 2025, '14BE39276', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1)),
('SM-FKL095', 'FORKLIFT', 'CPCD30-AG2', 'HANGCHA', 2025, '14BE39278', 'SALES AND OUTBOUND LOGISTICS', 'Active', (SELECT id FROM equipment_categories WHERE name = 'Forklift' LIMIT 1), (SELECT id FROM operators WHERE name = 'CHRISTOS Loannou' LIMIT 1))

ON CONFLICT (asset_tag) DO UPDATE SET
  type = EXCLUDED.type,
  model = EXCLUDED.model,
  manufacturer = EXCLUDED.manufacturer,
  year = EXCLUDED.year,
  serial_number = EXCLUDED.serial_number,
  current_location = EXCLUDED.current_location,
  status = EXCLUDED.status,
  category_id = EXCLUDED.category_id,
  assigned_operator_id = EXCLUDED.assigned_operator_id;
